name: finance_app
description: A comprehensive Flutter finance management application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.3

  # Database
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0

  # Utilities
  intl: ^0.20.0
  easy_localization: ^3.0.7
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  uuid: ^4.4.2

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  # Charts and Visualization
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^31.1.19

  # HTTP and networking
  http: ^1.2.2
  dio: ^5.7.0

  # File operations
  file_picker: ^8.1.2
  path_provider: ^2.1.4

  # Permissions and notifications
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3

  # Export functionality
  pdf: ^3.11.1
  csv: ^6.0.0

  # Encryption
  crypto: ^3.0.5
  flutter_secure_storage: ^9.2.2

  # Device info
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/

